worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;
events { worker_connections 64; }
http {
  access_log /dev/stdout;
  server {
    listen 18080;
    server_name bench.example;
    root /usr/share/nginx/html/bench.example;
  }
  server {
    listen 18080;
    server_name www.bench.example;
    root /usr/share/nginx/html/www.bench.example;
  }
  server {
    listen 18080;
    server_name staging.bench.example;
    root /usr/share/nginx/html/staging.bench.example;
  }
  server {
    listen 18080;
    server_name staging-api.bench.example;
    root /usr/share/nginx/html/staging-api.bench.example;
  }
  server {
    listen 18080;
    server_name admin.bench.example;
    root /usr/share/nginx/html/admin.bench.example;
  }
  server {
    listen 18080;
    server_name administrator.bench.example;
    root /usr/share/nginx/html/administrator.bench.example;
  }
  server {
    listen 18080;
    server_name admin-api.bench.example;
    root /usr/share/nginx/html/admin-api.bench.example;
  }
  server {
    listen 18080;
    server_name login.bench.example;
    root /usr/share/nginx/html/login.bench.example;
    location /login {
      alias /usr/share/nginx/html/login.bench.example/;
    }
  }
  server {
    listen 18080;
    server_name jenkins.bench.example;
    root /usr/share/nginx/html/jenkins.bench.example;
  }
  server {
    listen 18080;
    server_name grafana.bench.example;
    root /usr/share/nginx/html/grafana.bench.example;
  }
  server {
    listen 18080;
    server_name vpn.bench.example;
    root /usr/share/nginx/html/vpn.bench.example;
  }
  server {
    listen 18080;
    server_name devshop.bench.example;
    root /usr/share/nginx/html/devshop.bench.example;
  }
  server {
    listen 18080;
    server_name administrator-training.bench.example;
    root /usr/share/nginx/html/administrator-training.bench.example;
  }
  server {
    listen 18080;
    server_name administer.bench.example;
    root /usr/share/nginx/html/administer.bench.example;
  }
  server {
    listen 18080;
    server_name auth.bench.example;
    root /usr/share/nginx/html/auth.bench.example;
  }
  server {
    listen 18080;
    server_name auth-docs.bench.example;
    root /usr/share/nginx/html/auth-docs.bench.example;
  }
  server {
    listen 18080;
    server_name testimonial.bench.example;
    root /usr/share/nginx/html/testimonial.bench.example;
  }
  server {
    listen 18080;
    server_name grafana-training.bench.example;
    root /usr/share/nginx/html/grafana-training.bench.example;
  }
  server {
    listen 18080;
    server_name grafana-docs.bench.example;
    root /usr/share/nginx/html/grafana-docs.bench.example;
  }
  server {
    listen 18080;
    server_name jenkins-docs.bench.example;
    root /usr/share/nginx/html/jenkins-docs.bench.example;
  }
  server {
    listen 18080;
    server_name jenkins-training.bench.example;
    root /usr/share/nginx/html/jenkins-training.bench.example;
  }
  server {
    listen 18080;
    default_server;
    return 404;
  }
}
