"""Generate professional PDF security reports."""

from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

RISK_COLORS = {
    "high": (colors.HexColor("#FEE2E2"), colors.HexColor("#B91C1C")),
    "medium": (colors.HexColor("#FEF3C7"), colors.HexColor("#B45309")),
    "low": (colors.HexColor("#D1FAE5"), colors.HexColor("#047857")),
}


def _risk_style(risk_level: str) -> tuple:
    return RISK_COLORS.get(risk_level.lower(), (colors.HexColor("#F4F4F5"), colors.HexColor("#52525B")))


def _paragraph(text: str, style: ParagraphStyle) -> Paragraph:
    safe_text = (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return Paragraph(safe_text, style)


def _on_page(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#71717A"))
    canvas.drawCentredString(letter[0] / 2, 0.45 * inch, f"Page {canvas.getPageNumber()}")
    canvas.drawCentredString(
        letter[0] / 2,
        0.28 * inch,
        "Confidential — Generated by Sentinel Scout",
    )
    canvas.restoreState()


def build_pdf_report(
    domain: str,
    scan_data: dict[str, Any],
    report_content: dict[str, Any],
    generated_at: datetime | None = None,
) -> bytes:
    generated_at = generated_at or datetime.now()
    subdomains: list[dict[str, Any]] = scan_data.get("subdomains", [])
    executive_summary: list[str] = report_content.get("executive_summary", [])
    remediation: list[dict[str, Any]] = report_content.get("remediation", [])

    buffer = BytesIO()
    doc = BaseDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.85 * inch,
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="normal",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_on_page)])

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        textColor=colors.HexColor("#18181B"),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        textColor=colors.HexColor("#71717A"),
        spaceAfter=20,
    )
    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=colors.HexColor("#18181B"),
        spaceBefore=16,
        spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#3F3F46"),
        spaceAfter=10,
        alignment=TA_LEFT,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#52525B"),
        spaceAfter=4,
    )
    cell_style = ParagraphStyle(
        "Cell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#27272A"),
    )
    badge_style = ParagraphStyle(
        "Badge",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        alignment=TA_LEFT,
    )

    story: list[Any] = []

    story.append(_paragraph("Sentinel Scout Security Report", title_style))
    story.append(
        _paragraph(
            f"Generated {generated_at.strftime('%B %d, %Y at %I:%M %p')}",
            subtitle_style,
        )
    )
    story.append(_paragraph(f"<b>Target Domain:</b> {domain}", meta_style))
    story.append(_paragraph(f"<b>Subdomains Analyzed:</b> {len(subdomains)}", meta_style))
    if scan_data.get("truncation_note"):
        story.append(_paragraph(scan_data["truncation_note"], meta_style))

    story.append(Spacer(1, 0.15 * inch))
    story.append(_paragraph("Executive Summary", section_style))

    if executive_summary:
        for paragraph in executive_summary:
            story.append(_paragraph(paragraph, body_style))
    elif scan_data.get("summary"):
        story.append(_paragraph(scan_data["summary"], body_style))
    else:
        story.append(
            _paragraph(
                "No executive summary was generated for this assessment.",
                body_style,
            )
        )

    story.append(_paragraph("Findings", section_style))

    if subdomains:
        table_data: list[list[Any]] = [
            [
                _paragraph("<b>Subdomain</b>", cell_style),
                _paragraph("<b>Status</b>", cell_style),
                _paragraph("<b>Category</b>", cell_style),
                _paragraph("<b>Risk Level</b>", cell_style),
                _paragraph("<b>Notes</b>", cell_style),
            ]
        ]

        risk_row_colors: list[tuple] = []
        for item in subdomains:
            risk_level = str(item.get("risk_level", "Unknown"))
            bg_color, text_color = _risk_style(risk_level)
            risk_row_colors.append((bg_color, text_color))

            table_data.append(
                [
                    _paragraph(str(item.get("url", "")), cell_style),
                    _paragraph(str(item.get("status_code", "—")), cell_style),
                    _paragraph(str(item.get("category", "Unknown")), cell_style),
                    _paragraph(f"<font color='{text_color.hexval()}'>{risk_level}</font>", badge_style),
                    _paragraph(str(item.get("notes", "")), cell_style),
                ]
            )

        col_widths = [2.0 * inch, 0.55 * inch, 0.95 * inch, 0.75 * inch, 2.0 * inch]
        findings_table = Table(table_data, colWidths=col_widths, repeatRows=1)
        table_style = TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F4F4F5")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#18181B")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E4E4E7")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 1), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
            ]
        )

        for row_index, (bg_color, _) in enumerate(risk_row_colors, start=1):
            table_style.add("BACKGROUND", (3, row_index), (3, row_index), bg_color)

        findings_table.setStyle(table_style)
        story.append(findings_table)
    else:
        story.append(
            _paragraph("No live subdomains were discovered during this scan.", body_style)
        )

    story.append(_paragraph("Remediation", section_style))

    if remediation:
        for item in remediation:
            subdomain = item.get("subdomain", "Unknown")
            risk_level = item.get("risk_level", "Unknown")
            bg_color, text_color = _risk_style(str(risk_level))
            story.append(
                _paragraph(
                    f"<b>{subdomain}</b> "
                    f"<font color='{text_color.hexval()}'>[{risk_level} Risk]</font>",
                    body_style,
                )
            )
            steps = item.get("steps", [])
            if steps:
                for step in steps:
                    story.append(_paragraph(f"• {step}", body_style))
            else:
                story.append(_paragraph("• Review and remediate this finding.", body_style))
            story.append(Spacer(1, 0.08 * inch))
    else:
        story.append(
            _paragraph(
                "No High or Medium risk findings require remediation at this time.",
                body_style,
            )
        )

    doc.build(story)
    return buffer.getvalue()
